# Change these first
owner: Martijn-van-Kekem-Development # Your GitHub organization or username, where this repository lives
repo: MatchGear-Monitor # The name of this repository

workflowSchedule:
  responseTime: "0 * * * *"
  graphs: "5 * * * *"

sites:
  - name: Production API
    url: https://api-prod.matchgear.app/app-info
    method: GET
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
  - name: Beta API
    url: https://api-beta.matchgear.app/app-info
    method: GET
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
  - name: Website
    url: https://www.matchgear.app/en/
    maxResponseTime: 5000
  - name: Documentation website
    url: https://docs.matchgear.app/en/
    maxResponseTime: 5000

assignees:
  - martijnvankekem

status-website:
  cname: status.matchgear.app
  logoUrl: https://status.matchgear.app/logo.png
  favicon: https://status.matchgear.app/logo.png
  links:
    - rel: stylesheet
      href: https://status.matchgear.app/custom-style.css
  name: MatchGear Status
  introTitle: "**MatchGear**"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.matchgear.app
    - title: Help
      href: https://docs.matchgear.app

i18n:
  footer: Copyright &copy; - Martijn van Kekem Development
  up: Online
  down: Offline
  incidentCommentSummary: <span class="subtext">Posted at $DATE by $AUTHOR</span>