# Change these first
owner: Martijn-van-Kekem-Development # Your GitHub organization or username, where this repository lives
repo: MatchGear-Monitor # The name of this repository

sites:
  - name: API
    url: https://api-prod.matchgear.app/app-info
    method: GET
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200

assignees:
  - martijnvankekem

status-website:
  cname: status.matchgear.app
  logoUrl: /logo.png
  themeUrl: /custom.css
  name: MatchGear
  introTitle: "**MatchGear** status monitor."
  introMessage: This page shows the latest status of the MatchGear services.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.matchgear.app
    - title: Help
      href: https://docs.matchgear.app

i18n:
  footer: Copyright &copy; - Martijn van Kekem Development